-- Isole les identifiants personnalisés des identifiants natifs et fournit un
-- reset de classe atomique qui revient strictement aux données locales.
begin;

lock table public.created_spells in access exclusive mode;

create temporary table created_spell_id_map on commit drop as
select
  id as old_id,
  999999::bigint + row_number() over (order by id) as new_id,
  class_name
from public.created_spells;

-- Les overrides de propriétés étaient appliqués au sort natif et au sort
-- personnalisé portant le même ID. On les conserve pour les deux lors du remap.
insert into public.entity_overrides (
  id, entity_type, entity_key, field_key, value, previous_value,
  updated_at, updated_by, updated_by_label
)
select
  gen_random_uuid(), override_row.entity_type, mapping.new_id::text, override_row.field_key,
  override_row.value, override_row.previous_value, override_row.updated_at,
  override_row.updated_by, override_row.updated_by_label
from public.entity_overrides override_row
join created_spell_id_map mapping on override_row.entity_type = 'spell' and override_row.entity_key = mapping.old_id::text
on conflict (entity_type, entity_key, field_key) do nothing;

-- Une position est propre à une classe : elle peut donc être remappée sans ambiguïté.
update public.entity_overrides override_row
set entity_key = mapping.class_name || '/' || mapping.new_id::text
from created_spell_id_map mapping
where override_row.entity_type = 'spell_position'
  and override_row.entity_key = mapping.class_name || '/' || mapping.old_id::text;

update public.change_history history_row
set entity_key = mapping.class_name || '/' || mapping.new_id::text
from created_spell_id_map mapping
where history_row.entity_type = 'spell_position'
  and history_row.entity_key = mapping.class_name || '/' || mapping.old_id::text;

-- Les événements de cycle de vie désignent nécessairement le sort personnalisé.
update public.change_history history_row
set entity_key = mapping.new_id::text
from created_spell_id_map mapping
where history_row.entity_type = 'spell'
  and history_row.entity_key = mapping.old_id::text
  and history_row.field_key in ('__created__', '__deleted__');

-- Les autres historiques sont ambigus à cause de l'ancienne collision : ils
-- restent associés au natif et sont également copiés vers le personnalisé.
insert into public.change_history (
  id, entity_type, entity_key, field_key, old_value, new_value,
  changed_at, changed_by, changed_by_label
)
select
  gen_random_uuid(), history_row.entity_type, mapping.new_id::text, history_row.field_key,
  history_row.old_value, history_row.new_value, history_row.changed_at,
  history_row.changed_by, history_row.changed_by_label
from public.change_history history_row
join created_spell_id_map mapping on history_row.entity_type = 'spell' and history_row.entity_key = mapping.old_id::text
where history_row.field_key not in ('__created__', '__deleted__');

alter table public.created_spells alter column id set generated by default;

update public.created_spells spell
set id = mapping.new_id
from created_spell_id_map mapping
where spell.id = mapping.old_id;

alter table public.created_spells alter column id set generated always;

select setval(
  pg_get_serial_sequence('public.created_spells', 'id'),
  greatest(999999::bigint, coalesce((select max(id) from public.created_spells), 999999::bigint)),
  true
);

create function public.reset_spell_class(
  p_class_name text,
  p_native_spell_ids bigint[],
  p_targets jsonb
)
returns table (reset_count integer, deleted_custom_count integer, restored_native_count integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_custom_ids text[];
  v_native_ids text[];
  v_all_spell_ids text[];
  v_reset_count integer;
  v_deleted_custom_count integer;
  v_restored_native_count integer;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if nullif(btrim(p_class_name), '') is null
    or p_native_spell_ids is null
    or jsonb_typeof(p_targets) <> 'array' then
    raise exception 'Invalid class reset' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('reset_spell_class:' || p_class_name, 0));

  select coalesce(array_agg(id::text order by id), '{}'::text[])
  into v_custom_ids
  from public.created_spells
  where class_name = p_class_name;

  select coalesce(array_agg(id::text order by id), '{}'::text[])
  into v_native_ids
  from unnest(p_native_spell_ids) id;

  v_all_spell_ids := v_native_ids || v_custom_ids;
  select public.reset_overrides(p_targets) into v_reset_count;

  select count(*)::integer into v_deleted_custom_count
  from public.created_spells where class_name = p_class_name;
  select count(*)::integer into v_restored_native_count
  from public.deleted_native_spells where class_name = p_class_name;

  -- Garantit l'état baseline même si une écriture concurrente n'était pas dans p_targets.
  delete from public.entity_overrides
  where (entity_type = 'spell' and entity_key = any(v_all_spell_ids))
     or (entity_type = 'spell_position' and left(entity_key, length(p_class_name) + 1) = p_class_name || '/')
     or (entity_type = 'class_stat' and entity_key = p_class_name);

  delete from public.spell_comments where spell_id = any(v_custom_ids);
  delete from public.created_spells where class_name = p_class_name;
  delete from public.deleted_native_spells where class_name = p_class_name;

  return query select v_reset_count, v_deleted_custom_count, v_restored_native_count;
end;
$$;

revoke all on function public.reset_spell_class(text, bigint[], jsonb) from public, anon;
grant execute on function public.reset_spell_class(text, bigint[], jsonb) to authenticated;

commit;
