-- Catalogue collaboratif des toniques et mutations.
begin;

alter table public.entity_overrides
  drop constraint entity_overrides_entity_type_check,
  add constraint entity_overrides_entity_type_check check (entity_type in ('spell', 'spell_position', 'class_stat', 'tonic')),
  drop constraint entity_overrides_allowed_field,
  add constraint entity_overrides_allowed_field check (
    (entity_type = 'spell' and field_key in (
      'nom', 'pa', 'po', 'porteeModifiable', 'lancerEnLigne', 'ligneDeVue',
      'cc', 'ec', 'relance', 'parTour', 'parCible', 'icone', 'effets.normaux', 'effets.critiques'
    ))
    or (entity_type = 'spell_position' and field_key = 'position')
    or (entity_type = 'class_stat' and field_key in (
      'vie', 'pa', 'pm', 'vitalite', 'sagesse', 'force', 'intelligence', 'chance', 'agilite', 'initiative'
    ))
    or (entity_type = 'tonic' and field_key in ('title', 'effects', 'spellId'))
  );

alter table public.change_history
  drop constraint change_history_entity_type_check,
  add constraint change_history_entity_type_check
    check (entity_type in ('spell', 'spell_position', 'class_stat', 'tonic', 'import'));

create table public.created_tonics (
  id bigint generated by default as identity (start with 1000000) primary key,
  tonic jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid not null,
  created_by_label text not null
);

create table public.deleted_native_tonics (
  tonic_id bigint primary key,
  deleted_at timestamptz not null default now(),
  deleted_by uuid not null,
  deleted_by_label text not null
);

create table public.tonic_comments (
  id uuid primary key default gen_random_uuid(),
  tonic_id text not null check (length(tonic_id) > 0),
  body text not null check (length(btrim(body)) between 1 and 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null,
  created_by_label text not null,
  updated_by uuid not null,
  updated_by_label text not null
);

create index tonic_comments_tonic_created_idx on public.tonic_comments (tonic_id, created_at desc);
alter table public.created_tonics enable row level security;
alter table public.deleted_native_tonics enable row level security;
alter table public.tonic_comments enable row level security;
revoke all on table public.created_tonics, public.deleted_native_tonics, public.tonic_comments from public, anon, authenticated;
grant select, insert, update, delete on table public.tonic_comments to authenticated;

create policy tonic_comments_authenticated_read on public.tonic_comments for select to authenticated using ((select auth.uid()) is not null);
create policy tonic_comments_authenticated_insert on public.tonic_comments for insert to authenticated with check ((select auth.uid()) is not null);
create policy tonic_comments_authenticated_update on public.tonic_comments for update to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
create policy tonic_comments_authenticated_delete on public.tonic_comments for delete to authenticated using ((select auth.uid()) is not null);

create view public.public_created_tonics with (security_barrier = true) as
select id, tonic, created_at from public.created_tonics;
create view public.public_deleted_native_tonics with (security_barrier = true) as
select tonic_id, deleted_at from public.deleted_native_tonics;
revoke all on table public.public_created_tonics, public.public_deleted_native_tonics from public, anon, authenticated;
grant select on table public.public_created_tonics, public.public_deleted_native_tonics to anon, authenticated;

alter function public.apply_override(text, text, text, jsonb, jsonb) rename to apply_override_without_tonic;

create function public.apply_override(p_entity_type text, p_entity_key text, p_field_key text, p_new_value jsonb, p_baseline_value jsonb)
returns table (override_id uuid, history_id uuid, saved_at timestamptz, author_label text, was_changed boolean)
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user_id uuid := auth.uid(); v_label text; v_existing public.entity_overrides%rowtype;
  v_old jsonb; v_new jsonb := coalesce(p_new_value, 'null'::jsonb); v_baseline jsonb := coalesce(p_baseline_value, 'null'::jsonb);
  v_history uuid; v_override uuid; v_now timestamptz := clock_timestamp(); v_exists boolean;
begin
  if p_entity_type <> 'tonic' then
    return query select * from public.apply_override_without_tonic(p_entity_type, p_entity_key, p_field_key, p_new_value, p_baseline_value);
    return;
  end if;
  if v_user_id is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if nullif(p_entity_key, '') is null or p_field_key not in ('title', 'effects', 'spellId') then raise exception 'Invalid tonic field' using errcode = '22023'; end if;
  if p_field_key = 'title' and (jsonb_typeof(v_new) <> 'string' or nullif(btrim(v_new #>> '{}'), '') is null) then raise exception 'Title is required' using errcode = '22023'; end if;
  if p_field_key = 'effects' and (jsonb_typeof(v_new) <> 'array' or exists (select 1 from jsonb_array_elements(v_new) e where jsonb_typeof(e.value) <> 'string')) then raise exception 'Effects must be text lines' using errcode = '22023'; end if;
  if p_field_key = 'spellId' and jsonb_typeof(v_new) not in ('number', 'null') then raise exception 'Spell ID must be a number or null' using errcode = '22023'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email', ''), v_user_id::text);
  perform pg_advisory_xact_lock(hashtextextended(concat_ws(chr(31), p_entity_type, p_entity_key, p_field_key), 0));
  select * into v_existing from public.entity_overrides where entity_type = 'tonic' and entity_key = p_entity_key and field_key = p_field_key for update;
  v_exists := found; v_old := case when v_exists then v_existing.value else v_baseline end;
  if v_old = v_new then return query select case when v_exists then v_existing.id else null::uuid end, null::uuid, v_now, v_label, false; return; end if;
  insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label)
  values ('tonic',p_entity_key,p_field_key,v_old,v_new,v_now,v_user_id,v_label) returning id into v_history;
  insert into public.entity_overrides(entity_type,entity_key,field_key,value,previous_value,updated_at,updated_by,updated_by_label)
  values ('tonic',p_entity_key,p_field_key,v_new,v_old,v_now,v_user_id,v_label)
  on conflict (entity_type,entity_key,field_key) do update set value=excluded.value,previous_value=excluded.previous_value,updated_at=excluded.updated_at,updated_by=excluded.updated_by,updated_by_label=excluded.updated_by_label
  returning id into v_override;
  return query select v_override,v_history,v_now,v_label,true;
end; $$;

revoke all on function public.apply_override(text,text,text,jsonb,jsonb) from public, anon;
grant execute on function public.apply_override(text,text,text,jsonb,jsonb) to authenticated;

create function public.create_tonic(p_tonic jsonb)
returns table (tonic_id bigint, tonic jsonb, created_at timestamptz, author_label text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid(); v_label text; v_id bigint; v_now timestamptz := clock_timestamp();
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if jsonb_typeof(p_tonic) <> 'object' or p_tonic ->> 'kind' not in ('tonique','mutation') or p_tonic ->> 'category' not in ('palier1','palier2','rarus','mutation')
     or nullif(btrim(p_tonic ->> 'title'),'') is null or jsonb_typeof(p_tonic -> 'effects') <> 'array' then raise exception 'Invalid tonic' using errcode = '22023'; end if;
  if p_tonic ->> 'kind' = 'mutation' and (nullif(btrim(p_tonic ->> 'className'),'') is null or jsonb_typeof(p_tonic -> 'spellId') <> 'number') then raise exception 'A mutation requires a class and spell' using errcode = '22023'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email',''),v_user::text);
  insert into public.created_tonics(tonic,created_at,created_by,created_by_label) values (p_tonic - 'id',v_now,v_user,v_label) returning id into v_id;
  insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label) values ('tonic',v_id::text,'__created__','null',p_tonic,v_now,v_user,v_label);
  return query select v_id,p_tonic,v_now,v_label;
end; $$;

create function public.delete_tonic(p_tonic_id bigint) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid(); v_label text; v_custom public.created_tonics%rowtype; v_now timestamptz := clock_timestamp(); v_is_custom boolean := false;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email',''),v_user::text);
  select * into v_custom from public.created_tonics where id=p_tonic_id for update;
  v_is_custom := found;
  delete from public.entity_overrides where entity_type='tonic' and entity_key=p_tonic_id::text;
  if v_is_custom then
    delete from public.created_tonics where id=p_tonic_id;
    insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label) values ('tonic',p_tonic_id::text,'__deleted__',v_custom.tonic,'null',v_now,v_user,v_label);
  else
    insert into public.deleted_native_tonics(tonic_id,deleted_at,deleted_by,deleted_by_label) values (p_tonic_id,v_now,v_user,v_label) on conflict do nothing;
    insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label) values ('tonic',p_tonic_id::text,'__deleted__',jsonb_build_object('native',true),'null',v_now,v_user,v_label);
  end if;
end; $$;

create function public.reset_tonic(p_tonic_id bigint, p_baseline jsonb) returns integer
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid(); v_label text; v_row public.entity_overrides%rowtype; v_value jsonb; v_count integer := 0; v_now timestamptz;
begin
  if v_user is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if jsonb_typeof(p_baseline) <> 'object' then raise exception 'Invalid tonic baseline' using errcode='22023'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email',''),v_user::text);
  for v_row in select * from public.entity_overrides where entity_type='tonic' and entity_key=p_tonic_id::text for update loop
    v_value := coalesce(p_baseline -> v_row.field_key, 'null'::jsonb); v_now := clock_timestamp();
    if v_row.value <> v_value then
      insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label)
      values ('tonic',p_tonic_id::text,v_row.field_key,v_row.value,v_value,v_now,v_user,v_label);
    end if;
    delete from public.entity_overrides where id=v_row.id; v_count := v_count+1;
  end loop;
  return v_count;
end; $$;

create function public.restore_native_tonic(p_tonic_id bigint) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid(); v_label text; v_now timestamptz := clock_timestamp();
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email',''),v_user::text);
  delete from public.deleted_native_tonics where tonic_id=p_tonic_id;
  insert into public.change_history(entity_type,entity_key,field_key,old_value,new_value,changed_at,changed_by,changed_by_label) values ('tonic',p_tonic_id::text,'__restored__','null',jsonb_build_object('native',true),v_now,v_user,v_label);
end; $$;

create function public.set_tonic_comment_system_fields() returns trigger language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_user uuid := auth.uid(); v_label text; v_now timestamptz := clock_timestamp();
begin
  if v_user is null then raise exception 'Authentication required' using errcode='42501'; end if;
  v_label := coalesce(nullif(auth.jwt() ->> 'email',''),v_user::text); new.body := btrim(new.body);
  if tg_op='INSERT' then new.created_at:=v_now;new.created_by:=v_user;new.created_by_label:=v_label; else new.tonic_id:=old.tonic_id;new.created_at:=old.created_at;new.created_by:=old.created_by;new.created_by_label:=old.created_by_label; end if;
  new.updated_at:=v_now;new.updated_by:=v_user;new.updated_by_label:=v_label;return new;
end; $$;
create trigger tonic_comments_system_fields before insert or update on public.tonic_comments for each row execute function public.set_tonic_comment_system_fields();

revoke all on function public.create_tonic(jsonb), public.delete_tonic(bigint), public.restore_native_tonic(bigint), public.reset_tonic(bigint,jsonb) from public, anon;
grant execute on function public.create_tonic(jsonb), public.delete_tonic(bigint), public.restore_native_tonic(bigint), public.reset_tonic(bigint,jsonb) to authenticated;

commit;
